version: '3.1'
services:
  db:
    image: mysql:8.0.18
    ports:
      - '3306:3306'
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
  jdk:
    build: .
    ports:
      - '9999:9999'
    environment:
      - DB_URL=jdbc:mysql://db:3306/db
      - DB_USER=app
      - DB_PASS=pass